2018-04-24 15:55:21.449 - pyansibleinv -        dbbackup_mysql_list -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--day': '*',
 '--day_of_week': '*',
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--hour': '23',
 '--isets': '2',
 '--minute': '2',
 '--month': '*',
 '--rsets': '3',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'disable': False,
 'enable': False,
 'list': True,
 'status': False}
2018-04-24 15:55:21.449 - pyansibleinv -        dbbackup_mysql_list -  INFO - dict:{'template_only': False, 'rsets': '3', 'month': '*', 'cluster_id': None, 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'sshkey': '/opt/ansible/db.pem', 'atus': False, 'dbtype': 'mysql', 'able': False, 'day': '*', 'taskid': None, 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'workdir': '/opt/ansible', 'sable': False, 'sshpass': 'LR1!Ika', 'bug': False, 'minute': '2', 'uuid': '44489c8c-b4a6-4a01-b6f3-daf1e53e0970', 'ssh_try_limit': '600', 'task_id': '  external_task_id: 44489c8c-b4a6-4a01-b6f3-daf1e53e0970\n', 'hour': '23', 'day_of_week': '*', 'st': True, 'backup': True, 'isets': '2'}
2018-04-24 15:55:21.449 - pyansibleinv -        dbbackup_mysql_list -  INFO - create ansible hosts: /opt/ansible/inventory/44489c8c-b4a6-4a01-b6f3-daf1e53e0970/hosts
2018-04-24 15:55:21.450 - pyansibleinv -        dbbackup_mysql_list -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_list_44489c8c-b4a6-4a01-b6f3-daf1e53e0970.yml
2018-04-24 15:55:21.452 - pyansibleinv -        dbbackup_mysql_list -  INFO - check ssh availability
2018-04-24 15:55:21.452 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:55:21.521 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:55:21.522 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:55:21.592 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:55:21.593 - pyansibleinv -        dbbackup_mysql_list -  INFO - run ansible from python
2018-04-24 15:55:22.206 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:55:22.206 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY [list backup sets] ******************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:55:22.961 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:55:22.962 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [list mysql backup set] *************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:55:25.814 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mchanged: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:55:26.537 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:55:26.537 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - TASK [Record backup result] **************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:55:26.729 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:55:26.751 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - 
2018-04-24 15:55:26.751 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:55:26.751 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - [0;33mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m [0;33mchanged=1   [0m unreachable=0    failed=0
2018-04-24 15:55:26.848 - pyansibleinv - dbbackup_mysql_list_stdout -  INFO - --- Total Excution time: 0:00:05.399495 ---
2018-04-24 15:55:26.889 - pyansibleinv - dbbackup_mysql_list_stderr - ERROR - {"dcs-db-c00aee9f.iad1": {"backup_set02": {"2018_04_23-07_45_55": {"incrementals": [{"2018_04_23-09_41_33": {"size": "2.9 MB"}}, {"2018_04_23-09_41_19": {"size": "4.6 MB"}}], "size": "2.1 GB"}, "total_szie": "2.1 GB"}, "backup_set01": {"2018_04_23-09_42_05": {"incrementals": [], "size": "2.1 GB"}, "total_szie": "2.1 GB"}}}
