2018-04-24 15:50:26.018 - pyansibleinv -        dbbackup_mysql_query -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--day': '*',
 '--day_of_week': '*',
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--hour': '23',
 '--isets': '2',
 '--minute': '2',
 '--month': '*',
 '--rsets': '3',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'disable': False,
 'enable': False,
 'list': False,
 'status': True}
2018-04-24 15:50:26.018 - pyansibleinv -        dbbackup_mysql_query -  INFO - dict:{'template_only': False, 'rsets': '3', 'month': '*', 'cluster_id': None, 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'sshkey': '/opt/ansible/db.pem', 'atus': True, 'dbtype': 'mysql', 'able': False, 'day': '*', 'taskid': None, 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'workdir': '/opt/ansible', 'sable': False, 'sshpass': 'LR1!Ika', 'bug': False, 'minute': '2', 'uuid': '551f54ce-e450-4eee-a0a4-e922e1cf441d', 'ssh_try_limit': '600', 'task_id': '  external_task_id: 551f54ce-e450-4eee-a0a4-e922e1cf441d\n', 'hour': '23', 'day_of_week': '*', 'st': False, 'backup': True, 'isets': '2'}
2018-04-24 15:50:26.018 - pyansibleinv -        dbbackup_mysql_query -  INFO - create ansible hosts: /opt/ansible/inventory/551f54ce-e450-4eee-a0a4-e922e1cf441d/hosts
2018-04-24 15:50:26.019 - pyansibleinv -        dbbackup_mysql_query -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_query_551f54ce-e450-4eee-a0a4-e922e1cf441d.yml
2018-04-24 15:50:26.020 - pyansibleinv -        dbbackup_mysql_query -  INFO - check ssh availability
2018-04-24 15:50:26.021 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:50:26.089 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:50:26.089 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:50:26.158 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:50:26.159 - pyansibleinv -        dbbackup_mysql_query -  INFO - run ansible from python
2018-04-24 15:50:26.747 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:50:26.747 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY [crontab] ***************************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:50:27.488 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:50:27.488 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [query crontab] *********************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:50:30.180 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:50:30.901 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:50:30.902 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [Record crontab result] *************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:50:31.089 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:50:31.116 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:50:31.117 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
2018-04-24 15:50:31.117 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m changed=0    unreachable=0    failed=0
2018-04-24 15:50:31.218 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - --- Total Excution time: 0:00:05.200488 ---
2018-04-24 15:50:31.257 - pyansibleinv - dbbackup_mysql_query_stderr - ERROR - {"dcs-db-c00aee9f.iad1": {"job_context": "2 23 * * * /dbbackup/pyxbackup cron", "job_exists": true}}
