2018-04-24 15:35:16.840 - pyansibleinv -        dbbackup_mysql_query -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--day': '*',
 '--day_of_week': None,
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--hour': '23',
 '--isets': '2',
 '--minute': '2',
 '--month': '*',
 '--rsets': '3',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'disable': False,
 'enable': False,
 'list': False,
 'status': True}
2018-04-24 15:35:16.840 - pyansibleinv -        dbbackup_mysql_query -  INFO - dict:{'template_only': False, 'rsets': '3', 'month': '*', 'cluster_id': None, 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'sshkey': '/opt/ansible/db.pem', 'atus': True, 'dbtype': 'mysql', 'able': False, 'day': '*', 'taskid': None, 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'workdir': '/opt/ansible', 'sable': False, 'sshpass': 'LR1!Ika', 'bug': False, 'minute': '2', 'uuid': '685ffc33-a812-4b09-871b-20b95c3a4738', 'ssh_try_limit': '600', 'task_id': '  external_task_id: 685ffc33-a812-4b09-871b-20b95c3a4738\n', 'hour': '23', 'day_of_week': None, 'st': False, 'backup': True, 'isets': '2'}
2018-04-24 15:35:16.840 - pyansibleinv -        dbbackup_mysql_query -  INFO - create ansible hosts: /opt/ansible/inventory/685ffc33-a812-4b09-871b-20b95c3a4738/hosts
2018-04-24 15:35:16.841 - pyansibleinv -        dbbackup_mysql_query -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_query_685ffc33-a812-4b09-871b-20b95c3a4738.yml
2018-04-24 15:35:16.842 - pyansibleinv -        dbbackup_mysql_query -  INFO - check ssh availability
2018-04-24 15:35:16.843 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:35:16.911 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:35:16.911 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:35:16.981 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:35:16.981 - pyansibleinv -        dbbackup_mysql_query -  INFO - run ansible from python
2018-04-24 15:35:17.594 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:35:17.595 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY [crontab] ********************************************************************************************************************************************************************************
2018-04-24 15:35:18.345 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:35:18.345 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [query crontab] **************************************************************************************************************************************************************************
2018-04-24 15:35:21.250 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:35:21.951 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:35:21.951 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [Record crontab result] ******************************************************************************************************************************************************************
2018-04-24 15:35:22.197 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:35:22.221 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:35:22.221 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY RECAP ************************************************************************************************************************************************************************************
2018-04-24 15:35:22.221 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m changed=0    unreachable=0    failed=0
2018-04-24 15:35:22.254 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - --- Total Excution time: 0:00:05.414412 ---
2018-04-24 15:35:22.293 - pyansibleinv - dbbackup_mysql_query_stderr - ERROR - {"dcs-db-c00aee9f.iad1": {"job_context": "", "job_exists": false}}
