2018-04-24 15:16:09.407 - pyansibleinv -        dbbackup_mysql_query -  INFO - args:{'--cluster_id': None,
 '--data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57',
 '--day': '*',
 '--day_of_week': None,
 '--dbfqdn': 'dcs-db-c00aee9f.iad1',
 '--dbtype': 'mysql',
 '--hour': '23',
 '--isets': '2',
 '--minute': '2',
 '--month': '*',
 '--rsets': '3',
 '--ssh_try_limit': '600',
 '--sshkey': '/opt/ansible/db.pem',
 '--sshpass': 'LR1!Ika',
 '--taskid': None,
 '--template_only': False,
 '--workdir': '/opt/ansible',
 'dbbackup': True,
 'debug': False,
 'disable': False,
 'enable': False,
 'list': False,
 'status': True}
2018-04-24 15:16:09.407 - pyansibleinv -        dbbackup_mysql_query -  INFO - dict:{'template_only': False, 'rsets': '3', 'month': '*', 'cluster_id': None, 'data_host': 'dcs-db-c00aee9f.iad1:10.41.234.57', 'sshkey': '/opt/ansible/db.pem', 'atus': True, 'dbtype': 'mysql', 'able': False, 'day': '*', 'taskid': None, 'dbfqdn': 'dcs-db-c00aee9f.iad1', 'workdir': '/opt/ansible', 'sable': False, 'sshpass': 'LR1!Ika', 'bug': False, 'minute': '2', 'uuid': 'e0f4a769-280b-4a13-bbc6-f9d1b656126b', 'ssh_try_limit': '600', 'task_id': '  external_task_id: e0f4a769-280b-4a13-bbc6-f9d1b656126b\n', 'hour': '23', 'day_of_week': None, 'st': False, 'backup': True, 'isets': '2'}
2018-04-24 15:16:09.407 - pyansibleinv -        dbbackup_mysql_query -  INFO - create ansible hosts: /opt/ansible/inventory/e0f4a769-280b-4a13-bbc6-f9d1b656126b/hosts
2018-04-24 15:16:09.408 - pyansibleinv -        dbbackup_mysql_query -  INFO - craete ansible playbooks: /opt/ansible/dbbackup_mysql_query_e0f4a769-280b-4a13-bbc6-f9d1b656126b.yml
2018-04-24 15:16:09.409 - pyansibleinv -        dbbackup_mysql_query -  INFO - check ssh availability
2018-04-24 15:16:09.410 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:16:09.478 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:16:09.478 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Attempting to connect to 10.41.234.57 on port 22
2018-04-24 15:16:09.544 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - Connected to 10.41.234.57 on port 22
2018-04-24 15:16:09.545 - pyansibleinv -        dbbackup_mysql_query -  INFO - run ansible from python
2018-04-24 15:16:10.162 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:16:10.163 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY [crontab] ********************************************************************************************************************************************************************************
2018-04-24 15:16:10.952 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:16:10.953 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [query crontab] **************************************************************************************************************************************************************************
2018-04-24 15:16:13.671 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:16:14.387 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:16:14.387 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - TASK [Record crontab result] ******************************************************************************************************************************************************************
2018-04-24 15:16:14.583 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mok: [dcs-db-c00aee9f.iad1][0m
2018-04-24 15:16:14.605 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - 
2018-04-24 15:16:14.605 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - PLAY RECAP ************************************************************************************************************************************************************************************
2018-04-24 15:16:14.605 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - [0;32mdcs-db-c00aee9f.iad1[0m       : [0;32mok=2   [0m changed=0    unreachable=0    failed=0
2018-04-24 15:16:14.705 - pyansibleinv - dbbackup_mysql_query_stdout -  INFO - --- Total Excution time: 0:00:05.298761 ---
2018-04-24 15:16:14.706 - pyansibleinv - dbbackup_mysql_query_stderr - ERROR - ('e0f4a769-280b-4a13-bbc6-f9d1b656126b', ['dcs-db-c00aee9f.iad1'])
